### ISSUE TITLE
[Errno 2] No such file or directory: 'adversarial_dataset-A.npy'

### ISSUE THREAD

**Issue by abbasyazdinejad** [zhenghuatan/Audio-adversarial-examples#1]
Hi, after downloading adversarial_dataset-A, I have an error when run get_train_test.
Could you please guide me?

[Errno 2] No such file or directory: 'adversarial_dataset-A.npy'

**Comment by cnheider** [comment]
Hello @abbasyazdinejad, the exact preprocessing code (matlab script) for extracting the mfcc of the wavfile samples is to my knowledge not published.
Prior to executing the ’get_train_test’ function, he should run the ’save_data_to_array’ function to acquiring the ’adversarial_dataset-A.npy’.
 
The latter function loads the mfcc representations from matlab files and comprehends them into the missing file. https://github.com/zhenghuatan/Audio-adversarial-examples/blob/70daf3760967a7dbf0c70a965b9b477ceda4cfa2/adversarial_trainA_testA.py#L46
 
With some Matlab knowledge it should be readily achievable to compute the mfcc of the sample with the parameterisation given in the paper. I have devised some scripts that automates this process in a project of mine, do tell me if you would like me to share it.
